[workspace]
members = [
    "crates/rapid-core",
    "crates/rapid-cli",
    "crates/rapid-gui",
]
resolver = "2"

[workspace.package]
version = "1.0.2"
edition = "2021"
authors = ["Promahbubul"]
license = "MIT OR Apache-2.0"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
